Enable automake for libolgx
To try to debug Github Issue #2, I need to reproduce the issue first.

I managed to get Gentoo booted up on my ancient laptop since the newer
versions of Ubuntu seem to have become bloated enough that they can no
longer boot on older systems. Using Gentoo also has the nice feature that
it comes with all of the necessary X development headers in place. But
with Gentoo booted up, running `make` in the xview directory shows this:

```
(cd xview-3.2p1.4; bash Build-LinuxXView.bash libs)
imake-wrapper: running imake -DUseInstalled -I/run/initramfs/isoscan/git/github.com/olvwm/xview/xview-3.2p1.4/config -I/usr/lib/X11/config -I/usr/X11R6/lib/X11/config -I/usr/lib/X11/config -I/usr/X11R6/lib/X11/config in directory /run/initramfs/isoscan/git/github.com/olvwm/xview/xview-3.2p1.4/config
~/git/github.com/olvwm/xview/xview-3.2p1.4/imake: line 6: /usr/bin/X11/imake: No such file or directory
```

Rather than just run `sudo emerge x11-misc/imake` I wanted to be distro
agnostic and decided to build `imake` myself and ran it like this:
```
cd xview-3.2p1.4/lib
~/xbuild/bin/imake -I~/xbuild/lib64/X11/config -I../config
```

This successfully generated a makefile but if I try to run `make` it
fails with the following error:
...
olgx_impl.h:29:10: fatal error: olgx/olgx.h: No such file or directory
   29 | #include <olgx/olgx.h>

Fine, I should be able to install the headers myself, right?
Unfortunately `make install` wants to write to a immutable directory:
...
mkdir -p /usr/include/olgx
...

I could try to continue down this path and try to figure out how to
modify the Imakefiles to use relative paths but it seems so much easier
to just switch to automake instead, especially since the X folks seem to
have gone down that garden path already.

So I guess it is time to move on from imake to eliminate its hardcoded
paths. All of the Imakefiles are left as is for now until the automake
changes are complete.

Most of configure.ac was autogenerated using autoscan and then cleaned up
by browsing through the autotools docs (painfully) and then trying to use
various LLMs to try to fix up the various errors. In most cases they just
threw up "kitchen sink" suggestions and I needed to do further research to
narrow things down to the minimal required steps manually (which was even
more painful than just reading the docs). Overall the LLMs did not appear
to add much value other than introduce me to autoscan itself and help me
to figure out that I needed to `libtoolize --copy`.

Most of the rest of the stuff including the ugly bandaid hack to
pre-populate olgx.h was cooked up all by myself.

The changes were tested on the trusty old Ubuntu 16.04 distro that I use
as the development environment for olvwm as well as the newer Gentoo Live
ISO image running a 6.x kernel with newish gcc and X dev headers bundled.